[LangOptions]
LanguageName=简体中文
LanguageID=$0804
LanguageCodePage=936

[Messages]
WelcomeLabel1=欢迎使用 [name] 安装向导
WelcomeLabel2=此向导将帮助你在电脑上安装 [name/ver]。
WizardReady=安装程序已准备好开始安装 [name]。
ExitSetupTitle=退出安装程序
ExitSetupMessage=安装尚未完成。确定要退出安装程序吗？
AboutSetupMenuItem=关于安装程序...
ButtonBack=< 上一步(&B)
ButtonNext=下一步(&N) >
ButtonInstall=安装(&I)
ButtonCancel=取消
ButtonFinish=完成(&F)
ButtonOK=确定
ButtonYes=是(&Y)
ButtonYesToAll=全是(&A)
ButtonNo=否(&N)
ButtonNoToAll=全否(&O)
ButtonBrowse=浏览(&B)...
ButtonWizardBrowse=浏览(&R)...
ButtonNewFolder=新建文件夹(&M)
SelectLanguageTitle=选择安装语言
SelectLanguageLabel=选择安装时使用的语言。
ClickNext=点击“下一步”继续，或点击“取消”退出安装程序。
BrowseDialogTitle=浏览文件夹
BrowseDialogLabel=在下面的列表中选择一个文件夹，然后点击“确定”。
NewFolderName=新建文件夹
LicenseNotAccepted=我不同意此协议(&D)
WizardInfoBefore=信息
InfoBeforeLabel=请在继续安装前阅读以下重要信息。
InfoBeforeClickLabel=准备好继续安装后，点击“下一步”。
WizardInfoAfter=信息
InfoAfterLabel=请在继续安装前阅读以下重要信息。
InfoAfterClickLabel=准备好继续安装后，点击“下一步”。
WizardUserInfo=用户信息
UserInfoDesc=请输入您的信息。
UserInfoName=用户名(&U)：
UserInfoOrg=组织(&O)：
UserInfoSerial=序列号(&S)：
UserInfoNameRequired=您必须输入用户名。
WizardSelectDir=选择目标位置
SelectDirDesc=请选择 [name] 的安装位置。
SelectDirLabel3=安装程序将把 [name] 安装到以下文件夹。
SelectDirBrowseLabel=要继续请点击“下一步”。如果想选择其他文件夹，请点击“浏览”。
DiskSpaceGBLabel=至少需要 [gb] GB 的可用磁盘空间。
DiskSpaceMBLabel=至少需要 [mb] MB 的可用磁盘空间。
WizardSelectTasks=选择附加任务
SelectTasksDesc=请选择要执行的附加任务。
SelectTasksLabel2=请选择安装 [name] 时要执行的附加任务，然后点击“下一步”。
WizardSelectProgramGroup=选择开始菜单文件夹
SelectStartMenuFolderDesc=请选择开始菜单文件夹。
SelectStartMenuFolderLabel=请选择安装程序用于创建快捷方式的开始菜单文件夹。
WizardReady=准备安装
ReadyLabel1=安装程序已准备好开始安装 [name]。
ReadyLabel2a=点击“安装”继续，或点击“上一步”修改设置。
ReadyLabel2b=点击“安装”继续安装。
ReadyMemoUserInfo=用户信息：
ReadyMemoDir=目标位置：
ReadyMemoType=安装类型：
ReadyMemoComponents=已选择组件：
ReadyMemoGroup=开始菜单文件夹：
ReadyMemoTasks=附加任务：
DownloadingLabel2=正在下载文件...
ButtonStopDownload=停止下载(&S)
StopDownload=您确定要停止下载吗？
ErrorDownloadAborted=下载已中止
ErrorDownloadFailed=下载失败：%1 %2
ErrorDownloadSizeFailed=获取下载大小失败：%1 %2
ErrorProgress=无效的进度：%1 / %2
ErrorFileSize=文件大小错误：预期 %1，实际 %2
WizardPreparing=正在准备安装
PreparingDesc=安装程序正在准备安装 [name]。
WizardInstalling=正在安装
InstallingLabel=请稍候，安装程序正在将 [name] 安装到您的计算机上。
WizardFinished=安装完成
FinishedHeadingLabel=完成 [name] 安装向导
FinishedLabelNoIcons=安装程序已完成在您的计算机上安装 [name]。
FinishedLabel=安装程序已完成在您的计算机上安装 [name]。可通过已创建的快捷方式启动应用程序。
ClickFinish=点击“完成”退出安装程序。
FinishedRestartLabel=要完成 [name] 的安装，安装程序必须重新启动您的计算机。是否立即重新启动？
FinishedRestartMessage=要完成 [name] 的安装，安装程序必须重新启动您的计算机。%n%n是否立即重新启动？
ShowReadmeCheck=是，我要查看 README 文件
YesRadio=是，立即重新启动计算机(&Y)
NoRadio=否，我稍后重新启动计算机(&N)
RunEntryExec=运行 %1
RunEntryShellExec=查看 %1
ChangeDiskTitle=安装程序需要下一张磁盘
SelectDiskLabel2=请插入磁盘 %1，然后点击“确定”。%n%n如果此磁盘中的文件可以在下面显示的文件夹以外的位置找到，请输入正确路径或点击“浏览”。
PathLabel=路径(&P)：
FileNotInDir2=无法在“%2”中找到文件“%1”。请插入正确的磁盘或选择其他文件夹。
SelectDirectoryLabel=请选择下一张磁盘的位置。
SetupAborted=安装程序未完成。%n%n请修复问题后重新运行安装程序。
AbortRetryIgnoreSelectAction=请选择操作
AbortRetryIgnoreRetry=重试(&T)
AbortRetryIgnoreIgnore=忽略错误并继续(&I)
AbortRetryIgnoreCancel=取消安装(&C)
RetryCancelSelectAction=请选择操作
RetryCancelRetry=重试(&T)
RetryCancelCancel=取消(&C)
StatusClosingApplications=正在关闭应用程序...
StatusCreateDirs=正在创建目录...
StatusExtractFiles=正在解压文件...
StatusDownloadFiles=正在下载文件...
StatusCreateIcons=正在创建快捷方式...
StatusRegisterFiles=正在注册文件...
StatusRunProgram=正在启动程序...
ConfirmUninstall=你确定要完全删除 [name] 及其所有组件吗？
