#![allow(non_snake_case)]

mod core;
mod plugins;
mod services;
mod ui;
mod ui_access;
mod window_manager;

use qmetaobject::*;
use std::sync::Arc;

use ui::settings_window::load_persisted_settings;

// The qrc! macro invocation is generated by build.rs from resources/resources.qrc
// so the embedded resource tree stays in sync with the descriptor.
include!(concat!(env!("OUT_DIR"), "/resources_qrc.rs"));

/// 极简日志实现，避免引入 env_logger / jiff / anstream 等重依赖。
///
/// 仅依赖标准库 + `log` trait，输出 `[LEVEL] 消息` 到 stderr，
/// 可通过 `RUST_LOG` 环境变量调整级别（与 env_logger 的语法兼容）。
mod simple_logger {
    use log::{Level, LevelFilter, Metadata, Record};

    struct Logger;

    impl log::Log for Logger {
        fn enabled(&self, metadata: &Metadata) -> bool {
            metadata.level() <= log::max_level()
        }

        fn log(&self, record: &Record) {
            if !self.enabled(record.metadata()) {
                return;
            }
            let tag = match record.level() {
                Level::Error => "ERROR",
                Level::Warn => "WARN ",
                Level::Info => "INFO ",
                Level::Debug => "DEBUG",
                Level::Trace => "TRACE",
            };
            eprintln!("[{}] {}", tag, record.args());
        }

        fn flush(&self) {}
    }

    pub fn init() {
        let level = std::env::var("RUST_LOG")
            .ok()
            .and_then(|s| s.parse::<LevelFilter>().ok())
            .unwrap_or(LevelFilter::Info);
        log::set_max_level(level);
        let _ = log::set_boxed_logger(Box::new(Logger));
    }
}

fn deep_link_action_json(action: window_manager::DeepLinkAction) -> serde_json::Value {
    match action {
        window_manager::DeepLinkAction::OpenFile(path) => {
            serde_json::json!({ "action": "open", "file": path })
        }
        window_manager::DeepLinkAction::StartPlayer => serde_json::json!({ "action": "player" }),
        window_manager::DeepLinkAction::OpenSettings(category) => {
            serde_json::json!({ "action": "settings", "category": category })
        }
        window_manager::DeepLinkAction::OpenEditor => serde_json::json!({ "action": "editor" }),
        window_manager::DeepLinkAction::CastTo(device) => {
            serde_json::json!({ "action": "cast", "device": device })
        }
        window_manager::DeepLinkAction::Unknown(url) => {
            serde_json::json!({ "action": "unknown", "url": url })
        }
    }
}

fn main() {
    // Allow QML XMLHttpRequest to read local files (disabled by default in Qt 6.5+)
    std::env::set_var("QML_XHR_ALLOW_FILE_READ", "1");

    simple_logger::init();
    ::log::info!("Aeterna v{} starting...", env!("CARGO_PKG_VERSION"));

    let settings = load_persisted_settings();

    // 解析命令行参数
    let args: Vec<String> = std::env::args().collect();
    let force_mode = args.iter().any(|a| a == "--force" || a == "-f");
    let deep_link = args
        .iter()
        .position(|arg| arg == "--deep-link")
        .and_then(|index| args.get(index + 1))
        .cloned();
    if args.iter().any(|arg| arg == "--deep-link") && deep_link.is_none() {
        eprintln!("❌ --deep-link 需要一个 aeterna:// URL 参数。");
        return;
    }
    if let Some(url) = deep_link.as_deref() {
        if let Err(error) = window_manager::DeepLinkHandler::handle_deep_link(url) {
            eprintln!("❌ 无法处理 Deep Link: {}", error);
            return;
        }
    }

    // ── UI Access ──
    if settings.player.ui_access_enabled {
        ::log::info!("UI Access is enabled in settings, attempting to acquire...");
        unsafe {
            let result = ui_access::prepare_for_ui_access();
            if result == ui_access::ERROR_SUCCESS {
                ::log::info!("UI Access acquired successfully");
            } else {
                ::log::warn!("Failed to acquire UI Access, error code: 0x{:08X}", result);
            }
        }
    }

    // Register the embedded Qt resources (icons, fonts, etc.) with the
    // Qt resource system. The qrc!() macro above generates a `resources()`
    // function that does this idempotently.
    resources();
    ::log::info!("Qt resources registered");

    let _lock = match window_manager::SingleInstanceLock::acquire(force_mode) {
        Ok(Some(lock)) => lock,
        Ok(None) => {
            eprintln!(
                "❌ Aeterna 已在运行中，本次启动已退出。\n\
                 请检查系统托盘或任务栏中已有的 Aeterna 窗口。"
            );
            window_manager::notify_already_running();
            return;
        }
        Err(e) => {
            eprintln!("❌ 无法获取 Aeterna 单实例锁: {}", e);
            ::log::error!("Failed to acquire single-instance lock: {}", e);
            return;
        }
    };
    ::log::info!("Single instance lock acquired");

    if let Err(e) = window_manager::DeepLinkHandler::register_protocol() {
        ::log::warn!("Failed to register protocol handler: {}", e);
    }

    // ── Start HTTP API server in background ──
    // 纯 std 实现：直接在线程中运行 accept 循环，无需 tokio runtime。
    let api_config = services::http_api::ApiConfig::from_settings(&settings.http_api);
    let api_port = api_config.port;

    #[cfg(feature = "cast")]
    let share_runtime = {
        let lan_reachable = !matches!(
            api_config.bind_address.as_str(),
            "127.0.0.1" | "::1" | "localhost"
        ) && !api_config.token.trim().is_empty();
        let cast_service = Arc::new(services::cast::CastService::with_config(
            services::cast::CastConfig {
                mdns_enabled: settings.cast.mdns_enabled,
                advertise_on_lan: settings.cast.advertise_on_lan,
                device_name: settings.cast.device_name.clone(),
                port: api_port,
                allow_remote_control: settings.cast.allow_remote_control,
                auto_accept: settings.cast.auto_accept,
                share_enabled: settings.cast.allow_remote_control,
                api_reachable_on_lan: lan_reachable,
            },
        ));
        let runtime = Arc::new(services::share_runtime::ShareRuntime::new(
            settings.clone(),
            cast_service.clone(),
        ));
        let _ = services::share_runtime::install(runtime.clone());
        std::thread::spawn(move || match cast_service.start() {
            Ok(()) => ::log::info!("Cast service started"),
            Err(e) => ::log::warn!("Cast service not started: {}", e),
        });
        runtime
    };

    #[cfg(not(feature = "cast"))]
    let share_runtime = {
        let runtime = Arc::new(services::share_runtime::ShareRuntime::new(settings.clone()));
        let _ = services::share_runtime::install(runtime.clone());
        runtime
    };

    if settings.basic.auto_load_last {
        let _ = share_runtime.restore_active_config();
    }
    #[cfg(feature = "cast")]
    {
        let share_runtime = share_runtime.clone();
        std::thread::spawn(move || {
            std::thread::sleep(std::time::Duration::from_secs(2));
            share_runtime.share_active_config();
        });
    }
    let api_service = Arc::new(services::http_api::HttpApiService::with_config_and_runtime(
        api_config,
        share_runtime.clone(),
    ));
    let _ = services::http_api::install(api_service.clone());
    std::thread::spawn(move || {
        if let Err(e) = api_service.start() {
            ::log::error!("HTTP API supervisor failed: {}", e);
        }
    });
    ::log::info!("HTTP API supervisor started for port {}", api_port);

    // 插件能力尚未面向用户开放，因此不扫描或加载外部插件。这样既避免
    // 启动时的额外 I/O 和线程开销，也不会让未完成插件影响考场运行。

    // ── Setup QML and start UI ──
    let mut engine = QmlEngine::new();
    engine.set_property("applicationName".into(), QString::from("Aeterna").into());
    engine.set_property("organizationName".into(), QString::from("Aeterna").into());
    engine.set_property(
        "organizationDomain".into(),
        QString::from("aeterna.app").into(),
    );

    ui::main_window::register_types(&mut engine);

    let main_url = QUrl::from(QString::from("qrc:/qml/MainWindow.qml"));
    eprintln!("Loading QML from: qrc:/qml/MainWindow.qml");
    engine.load_url(main_url);

    if let Some(action) = window_manager::take_pending_deep_link() {
        let deep_link_json = serde_json::to_string(&deep_link_action_json(action))
            .unwrap_or_else(|_| "{}".to_string());
        engine.invoke_method_noreturn(
            QByteArray::from("handleDeepLink"),
            &[QString::from(deep_link_json).into()],
        );
    }

    ::log::info!("Application started");
    engine.exec();
}
