#![allow(non_snake_case)]

mod core;
mod services;
mod ui;
mod ui_access;
mod window_manager;

use qmetaobject::*;
use std::sync::Arc;

// The qrc! macro invocation is generated by build.rs from resources/resources.qrc
// so the embedded resource tree stays in sync with the descriptor.
include!(concat!(env!("OUT_DIR"), "/resources_qrc.rs"));

fn main() {
    // Allow QML XMLHttpRequest to read local files (disabled by default in Qt 6.5+)
    std::env::set_var("QML_XHR_ALLOW_FILE_READ", "1");

    env_logger::init();
    ::log::info!("Aeterna v{} starting...", env!("CARGO_PKG_VERSION"));

    // 解析命令行参数
    let args: Vec<String> = std::env::args().collect();
    let force_mode = args.iter().any(|a| a == "--force" || a == "-f");

    // ── UI Access ──
    if is_ui_access_enabled() {
        ::log::info!("UI Access is enabled in settings, attempting to acquire...");
        unsafe {
            let result = ui_access::prepare_for_ui_access();
            if result == ui_access::ERROR_SUCCESS {
                ::log::info!("UI Access acquired successfully");
            } else {
                ::log::warn!("Failed to acquire UI Access, error code: 0x{:08X}", result);
            }
        }
    }

    // Register the embedded Qt resources (icons, fonts, etc.) with the
    // Qt resource system. The qrc!() macro above generates a `resources()`
    // function that does this idempotently.
    resources();
    ::log::info!("Qt resources registered");

    let _lock = window_manager::SingleInstanceLock::acquire(force_mode);
    if _lock.is_none() {
        eprintln!(
            "❌ Aeterna 已在运行中，本次启动已退出。\n\
             请检查系统托盘或任务栏中已有的 Aeterna 窗口。\n\
             使用 --force 参数可强制启动新实例。"
        );
        window_manager::notify_already_running();
        return;
    }
    ::log::info!("Single instance lock acquired");

    if let Err(e) = window_manager::DeepLinkHandler::register_protocol() {
        ::log::warn!("Failed to register protocol handler: {}", e);
    }

    // ── Shared tokio runtime ──
    // 所有异步服务（HTTP API, Cast）共用同一个 multi-thread runtime，
    // 避免多个独立 runtime 竞争系统线程。
    let shared_rt =
        Arc::new(tokio::runtime::Runtime::new().expect("Failed to create shared tokio runtime"));

    // ── Start HTTP API server in background ──
    let api_service = Arc::new(services::http_api::HttpApiService::new());
    {
        let api_service = api_service.clone();
        let rt = shared_rt.clone();
        std::thread::spawn(move || {
            rt.block_on(async {
                if let Err(e) = api_service.start().await {
                    ::log::error!("HTTP API server failed: {}", e);
                }
            });
        });
    }
    ::log::info!("HTTP API server starting on port 9527");

    // 插件能力尚未面向用户开放，因此不扫描或加载外部插件。这样既避免
    // 启动时的额外 I/O 和线程开销，也不会让未完成插件影响考场运行。

    // ── Start Cast Service (disabled by default) ──
    let cast_service = Arc::new(services::cast::CastService::with_config(
        services::cast::CastConfig {
            enabled: false,
            ..Default::default()
        },
    ));

    // ── Setup QML and start UI ──
    let mut engine = QmlEngine::new();
    engine.set_property("applicationName".into(), QString::from("Aeterna").into());
    engine.set_property("organizationName".into(), QString::from("Aeterna").into());
    engine.set_property(
        "organizationDomain".into(),
        QString::from("aeterna.app").into(),
    );

    ui::main_window::register_types(&mut engine);

    let main_url = QUrl::from(QString::from("qrc:/qml/MainWindow.qml"));
    eprintln!("Loading QML from: qrc:/qml/MainWindow.qml");
    engine.load_url(main_url);

    {
        let cast_service = cast_service.clone();
        let rt = shared_rt.clone();
        std::thread::spawn(move || {
            // CastService::start 是同步的（内部已 spawn 发现线程），
            // 但需要 rt 保持存活以支持 cast_to_device 中的异步请求。
            let _rt = rt;
            match cast_service.start() {
                Ok(()) => ::log::info!("Cast service started"),
                Err(e) => ::log::warn!("Cast service not started: {}", e),
            }
        });
    }

    ::log::info!("Application started");
    engine.exec();
}

/// 读取 settings.json 检查 UI Access 是否启用
fn is_ui_access_enabled() -> bool {
    let path = crate::core::utils::aeterna_config_dir().join("settings.json");
    match std::fs::read_to_string(&path) {
        Ok(content) => match serde_json::from_str::<serde_json::Value>(&content) {
            Ok(json) => json
                .get("player")
                .and_then(|p| p.get("ui_access_enabled"))
                .and_then(|v| v.as_bool())
                .unwrap_or(false),
            Err(_) => false,
        },
        Err(_) => false,
    }
}
