#![allow(non_snake_case)]

mod core;
mod ui;
mod services;
mod plugins;
mod window_manager;
mod ui_access;

use qmetaobject::*;
use std::sync::Arc;

// The qrc! macro invocation is generated by build.rs from resources/resources.qrc
// so the embedded resource tree stays in sync with the descriptor.
include!(concat!(env!("OUT_DIR"), "/resources_qrc.rs"));

fn main() {
    // Allow QML XMLHttpRequest to read local files (disabled by default in Qt 6.5+)
    std::env::set_var("QML_XHR_ALLOW_FILE_READ", "1");

    env_logger::init();
    ::log::info!("Aeterna v{} starting...", env!("CARGO_PKG_VERSION"));

    // ── UI Access: 在 QML 引擎启动前检查并获取 UIAccess 权限 ──
    // 参考 uiaccess-master 项目原理：
    // 如果用户在设置中启用了 UI Access，则尝试获取 UIAccess 权限。
    // 成功时进程会以新令牌重启，旧进程退出，新进程继承所有设置。
    // 仅在 Windows 平台有效。
    if is_ui_access_enabled() {
        ::log::info!("UI Access is enabled in settings, attempting to acquire...");
        unsafe {
            let result = ui_access::prepare_for_ui_access();
            if result == ui_access::ERROR_SUCCESS {
                ::log::info!("UI Access acquired successfully");
            } else {
                ::log::warn!("Failed to acquire UI Access, error code: 0x{:08X}", result);
            }
        }
    }

    // Register the embedded Qt resources (icons, fonts, etc.) with the
    // Qt resource system. The qrc!() macro above generates a `resources()`
    // function that does this idempotently.
    resources();
    ::log::info!("Qt resources registered");

    let _lock = window_manager::SingleInstanceLock::acquire();
    if _lock.is_none() {
        return;
    }
    ::log::info!("Single instance lock acquired");

    if let Err(e) = window_manager::DeepLinkHandler::register_protocol() {
        ::log::warn!("Failed to register protocol handler: {}", e);
    }

    // ── Start HTTP API server in background ──
    let api_service = Arc::new(services::http_api::HttpApiService::new());
    let api_service_clone = api_service.clone();
    std::thread::spawn(move || {
        let rt = match tokio::runtime::Runtime::new() {
            Ok(rt) => rt,
            Err(e) => {
                ::log::error!("Failed to create HTTP API runtime: {}", e);
                return;
            }
        };
        rt.block_on(async {
            if let Err(e) = api_service_clone.start().await {
                ::log::error!("HTTP API server failed: {}", e);
            }
        });
    });
    ::log::info!("HTTP API server starting on port 9527");

    // ── Initialize Plugin Manager ──
    let plugin_manager = Arc::new(plugins::PluginManager::new());
    {
        let plugin_manager = plugin_manager.clone();
        std::thread::spawn(move || {
            match plugin_manager.load_all() {
                Ok(count) => ::log::info!("Loaded {} plugins", count),
                Err(e) => ::log::warn!("Failed to load plugins: {}", e),
            }
        });
    }

    // ── Start Cast Service (disabled by default) ──
    let cast_service = Arc::new(services::cast::CastService::with_config(
        services::cast::CastConfig {
            enabled: false,
            ..Default::default()
        }
    ));

    // ── Setup QML and start UI ──
    // All QML files and icons are embedded via the qrc! macro generated from
    // resources/resources.qrc, so load the main window directly from the
    // resource tree instead of extracting files to a temporary directory.
    let mut engine = QmlEngine::new();
    engine.set_property("applicationName".into(), QString::from("Aeterna").into());
    engine.set_property("organizationName".into(), QString::from("Aeterna").into());
    engine.set_property("organizationDomain".into(), QString::from("aeterna.app").into());

    ui::main_window::register_types(&mut engine);

    let main_url = QUrl::from(QString::from("qrc:/qml/MainWindow.qml"));
    eprintln!("Loading QML from: qrc:/qml/MainWindow.qml");
    engine.load_url(main_url);

    {
        let cast_service = cast_service.clone();
        std::thread::spawn(move || {
            match cast_service.start() {
                Ok(()) => ::log::info!("Cast service started"),
                Err(e) => ::log::warn!("Cast service not started: {}", e),
            }
        });
    }

    ::log::info!("Application started");
    engine.exec();
}

/// 读取 settings.json 检查 UI Access 是否启用
fn is_ui_access_enabled() -> bool {
    let path = crate::core::utils::aeterna_config_dir().join("settings.json");
    match std::fs::read_to_string(&path) {
        Ok(content) => match serde_json::from_str::<serde_json::Value>(&content) {
            Ok(json) => json
                .get("player")
                .and_then(|p| p.get("ui_access_enabled"))
                .and_then(|v| v.as_bool())
                .unwrap_or(false),
            Err(_) => false,
        },
        Err(_) => false,
    }
}
